### ISSUE TITLE
Can't run example.

### ISSUE THREAD

**Issue by lyuben-todorov** [sclabs/treeshaker#5] opened 2021-02-08 15:36 UTC
Following all of the steps from the README I arrive at the following result:
```bash
  File "/home/lyubentodorov/.local/lib/python3.9/site-packages/treeshaker/treeshaker.py", line 96, in process_module
    raise ImportError('could not import target module %s'
ImportError: could not import target module mypkg.target
```
I'm not much of a python guy, but the following works in the same virtual environment:
```python
import mypkg
// OR
from mypkg import target
```

Otherwise this seems like an exceptionally useful package if it does what I think it does. What I want to do is this:
I have a small python script that drags in one smallish dependency. I want to threeshake my dependencies to reduce the size of my final dependency package (I pack them in a zip to use on a container with limited resource).

**Comment by thomasgilgenast** [comment] 2021-02-09 03:52
Thanks for trying out the tool!

At a high level, I think treeshaker could be a good fit for what you're trying to do. There is one caveat I should mention which is that if your dependencies include packages that use C extensions, treeshaker currently has no mechanisms to re-compile those (your treeshaken code can still depend on these C extension-containing dependencies via the `requirements.txt` file that treeshaker will generate, but you likely won't be able to treeshake those dependencies to make them smaller).

I'd be happy to help try to get to bottom of what's going wrong here. I couldn't reproduce the error you're seeing when I ran the commands in the demo section of the README:

```
git clone https://github.com/sclabs/treeshaker.git
cd treeshaker
# virtualenv venv  # to make sure I'm using a python3.9 venv, I changed this command to the line below
python3.9 -m venv venv
source venv/bin/activate
pip install . ./examples/mypkg ./examples/otherpkg ./examples/externaldep ./examples/otherdep
treeshaker --config examples/treeshaker.cfg
```

but I am hopeful that we can still figure this out.

I will preface this by saying that Python's dependency management and where Python looks for modules to import can get pretty complicated, so if there are questions or things that just don't make sense I'd be happy to try to explain.

Just in case these turn out to be useful:

After running the `pip install` step with the virtualenv active (installing both treeshaker and the target package), if I check what's in the virtualenv by running `pip freeze` I see:

```
(venv)$ pip freeze
altgraph==0.17
click==7.1.2
externaldep==0.0.1
fire==0.4.0
modulegraph==0.18
mypkg==0.0.1
otherdep==0.0.1
otherpkg==0.0.1
pip-tools==5.5.0
requirements-parser==0.2.0
six==1.15.0
termcolor==1.1.0
treeshaker==0.0.3
```

It might be worth running `pip freeze` just to confirm that treeshaker and mypkg are definitely in the same environment.

Another angle on this is you can confirm where Python is loading the treeshaker module from. If you run python from the repo root (basically what the README example assumes), Python should find treeshaker right there in the git checkout (because the current working directory is the first place Python looks for a package during import):

```
(venv)$ python
>>> from treeshaker import treeshaker
>>> treeshaker.__file__
'.../git/treeshaker/treeshaker/treeshaker.py'
```

If I try the same thing, but running python from a different directory (in this example I copy `examples/` from the git repo to a different location and run python from there):

```
$ mkdir ../treeshaker-examples
$ cp -r examples ../treeshaker-examples/examples
$ cd ../treeshaker-examples
$ python3.9 -m venv venv
$ source venv/bin/activate
(venv)$ pip install treeshaker ./examples/mypkg ./examples/otherpkg ./examples/externaldep ./examples/otherdep
(venv)$ python
>>> from treeshaker import treeshaker
>>> treeshaker.__file__
'.../git/treeshaker-examples/venv/lib/python3.9/site-packages/treeshaker/treeshaker.py'
```

I'm just mentioning this because in your output I see that the `treeshaker.py` module file is being loaded from `~/.local/lib/python3.9/site-packages` which might not be a virtualenv (unless you named your virtualenv `.local`).

Technically, we're invoking treeshaker by calling the `treeshaker` entry point executable script directly on the command line (rather than importing it from Python), so we can also check where this executable is (it should also be inside the virtualenv):

```
(venv)$ which treeshaker
.../git/treeshaker/venv/bin/treeshaker
```

This workflow does feel a bit weird: I'm basically recommending that users create a new virtual environment specifically for the purposes of treeshaking, into which both the treeshaking tool and the package we want to treeshake are installed together.

One other thing I can think of at the moment that might help us debug this: treeshaker depends on [modulegraph](https://modulegraph.readthedocs.io/en/latest/find_modules.html) to build a graph of dependencies between modules. If it turns out that treeshaker and mypkg really are in the same virtualenv, we can take a closer look at what exactly modulegraph is finding. For example, if I tell modulegraph to look for treeshaker and mypkg, it finds the `__init__.py` files of both of these packages in the virtualenv they are installed in:

```
(venv)$ python
>>> from modulegraph.find_modules import find_modules, parse_mf_results
>>> mg = find_modules(includes=('treeshaker', 'mypkg'))
>>> modules, extensions = parse_mf_results(mg)
>>> [module.filename for module in modules if 'treeshaker' in module.filename or 'mypkg' in module.filename]
['.../git/treeshaker-examples/venv/lib/python3.9/site-packages/mypkg/__init__.py', '.../git/treeshaker-examples/venv/lib/python3.9/site-packages/treeshaker/__init__.py']
```

Additionally, the first few lines of stdout I see when running the `treeshaker` step (which should be printed before you reach the line where you experience the crash) are:

```
(venv)$ treeshaker --config examples/treeshaker.cfg
parsed 20 requirements from requirements.txt
constructing module import graph
found 738 nodes in the module import graph
```

If you're seeing different numbers of nodes, etc. that could be a hint as to what modules modulegraph is finding.

**Comment by lyuben-todorov** [comment] 2021-02-09 13:28
Thanks for the quick response!

I keep forgetting about python's beautiful module system. Now removing my global treeshaker version and running the one in the venv:
```bash
$ which treeshaker
/home/lyubentodorov/Projects/treeshaker/venv/bin/treeshaker
```
and the output of treeshaker now:
```
$ treeshaker --config examples/treeshaker.cfg

parsed 20 requirements from requirements.txt                           
constructing module import graph
found 665 nodes in the module import graph
found 3 modules imported from target packages
found 2 modules imported from 1 external requirements

```
Now onto my situation:
```
$ tree -I venv   
.
├── build_target
│   └── __init__.py
├── requirements.txt
├── treeshaker.cfg
└── validator
    ├── setup.py
    └── validator
        ├── __init__.py
        └── validate.py

3 directories, 6 files
```
I've made my own package (or at least attempted to), following the structure of your mypkg. It has an empty `__init__.py` and a `setup.py`. This is my requirements.txt:
```bash
attrs==20.3.0
jsonschema==3.2.0
openapi-spec-validator==0.2.9 # root dependency
pyrsistent==0.17.3
PyYAML==5.4.1
six==1.15.0
```
Now I do the following:
```bash
$ python3.9 -m venv venv
$ pip install -r requirements.txt  
$ pip install --no-cache-dir ./validator  # another mistake was installing 'validator' instead of my own package
$ pip install treeshaker
```
My `threeshaker.cfg` is the following:
```
[targets]
validator.validate

[target]
requirements_file=requirements.txt

# I want all of my dependencies to be 'packed', to my understanding, maybe this doesn't make sense
target_packages=
    validator
    openapi_spec_validator
    attrs
    jsonschema
    openapi-spec-validator
    pyrsistent
    PyYAML
    six

add_init_py=True

readme=<outdir>.md

post_build_commands=
    ls
    echo "built output in <outdir>/"

[target:validator.validate]
outdir=build_target
```
I've noticed that treeshaker breaks when `readme=<outdir>.md` is missing.

And this is my script (from validator.validate):
```python
import os, sys
from openapi_spec_validator import validate_spec 
from openapi_spec_validator.loaders import ExtendedSafeLoader
# guessing treeshaker builds the graph from only these imports ^

def validate_wrapper():

    try:
        import yaml
    except ImportError:
        import pathlib
        p = pathlib.Path(__file__).parent.absolute()
        sys.path.insert(0, os.path.join(p, "yaml.zip"))
        import yaml # here the yaml dependency is loaded from a separate pre-existing zip

    spec_path = './default.yaml'
    if len(sys.argv) > 1:
        spec_path = str(sys.argv[1])

    def load_yaml(path):
        try:
            with open(path) as fh:
                return yaml.load(fh, Loader = ExtendedSafeLoader)
        except IOError as err:
            raise SystemExit(err)

    spec_yaml = load_yaml(spec_path)

    validate_spec(spec_yaml)
```
I've managed to produce a satisfyingly small output of 350K compared to 6.5M which I get by running `pip install -t ...`. However I'm unsure if what I've done is really functional or how I can use the output I get. 

Naively trying (running it as a script):
```
$ python build_target/validate.py ...

Traceback (most recent call last):
  File "/home/lyubentodorov/Projects/oapi_validator/package/build_target/validate.py", line 2, in <module>
    from .openapi_spec_validator import validate_spec
ImportError: attempted relative import with no known parent package
```
and then trying to import it as a module:
```
$ cd build_target
$ python
>>> from validator import validate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lyubentodorov/Projects/oapi_validator/package/venv/lib/python3.9/site-packages/validator/validate.py", line 2, in <module>
    from openapi_spec_validator import validate_spec
  File "/home/lyubentodorov/Projects/oapi_validator/package/build_target/openapi_spec_validator.py", line 2, in <module>
    from .shortcuts import (
ImportError: attempted relative import with no known parent package
>>> 
```
It appears that it does indeed register `validator` as a package? but setting up the `validate` module fails. `shortcuts.py` exists in `build_target`.
To me it doesn't matter if I run my code as a script or import it as a module externally. 

I'm kind of getting lost in python's module system.

My biggest mistakes here were not treating python's module namespacing properly.

**Comment by thomasgilgenast** [comment] 2021-02-16 03:17
Sorry to be so slow in getting back to this.

Just for testing, I made some minor changes to your `validator/validate.py`:

```
import sys

import yaml
from openapi_spec_validator import validate_spec
from openapi_spec_validator.loaders import ExtendedSafeLoader


def validate_wrapper():
    spec_path = "./default.yaml"
    if len(sys.argv) > 1:
        spec_path = str(sys.argv[1])

    def load_yaml(path):
        try:
            with open(path) as fh:
                return yaml.load(fh, Loader=ExtendedSafeLoader)
        except IOError as err:
            raise SystemExit(err)

    spec_yaml = load_yaml(spec_path)

    validate_spec(spec_yaml)


if __name__ == '__main__':
    validate_wrapper()
```

You might have some custom `yaml` package in a zipfile that you require for your specialized use case, but just to get off the ground (and so that I could try reproducing what you have since I don't have your `yaml.zip`) I used the implementation of `yaml.load()` provided by the PyYAML package (which is already listed in your dependencies).

I also added the line `validator==0.0.1` (or whatever version you specified in validator's `setup.py`) to `requirements.txt`. The `requirements.txt` file used by treeshaker is expected to contain both target modules and dependencies.

Finally, I modified the `target_packages` option under the `[target]` section of `treeshaker.cfg` so that instead of listing `PyYAML` it lists `yaml`. Similarly, you don't need to list `openapi-spec-validator`, you only need `openapi_spec_validator`. This is quite confusing, but it is because some packages have a certain name that they are known by on the Python package index (PyYAML, openapi-spec-validator) but use a different name for the actual package (`import yaml`, `import openapi_spec_validator`). This is not explained in the treeshaker README, but the `target_packages` option is supposed to list the names of the actual packages, not the names they go by on the package index.

Running treeshaker after these changes creates the following script at `build_target/validate.py`:

```
import sys

import .yaml
from .openapi_spec_validator import validate_spec
from .loaders import ExtendedSafeLoader


def validate_wrapper():
    spec_path = "./default..yaml"
    if len(sys.argv) > 1:
        spec_path = str(sys.argv[1])

    def load_.yaml(path):
        try:
            with open(path) as fh:
                return .yaml.load(fh, Loader=ExtendedSafeLoader)
        except IOError as err:
            raise SystemExit(err)

    spec_.yaml = load_.yaml(spec_path)

    validate_spec(spec_.yaml)


if __name__ == '__main__':
    validate_wrapper()
```

Unfortunately, this contains syntax errors (like `def load_.yaml(path):`) which are due to treeshaker's import rewriting being way too shortsighted. treeshaker copies the `yaml` module to `build_target/yaml.py` and then attempts to rewrite imports that look like `import yaml` to `import .yaml`(turning them into a relative import pointing to `build_target/yaml.py`, a module in the same package as all the other copied files, ensuring that the import works even when the PyYAML package is not installed). treeshaker's current import rewriting logic simply replaces all occurrences of `yaml` with `.yaml` (by just doing `str.replace()` on the entire contents of the module's source code file), which is clearly not a good idea as shown by the mangled output above, because it replaces function names and other identifiers that contain "yaml".

There are at least three ways I can think of that I could use to improve the import rewriting:
1. Parse the AST of the module, change the names of the modules only in import statements, and then convert the edited AST back to code with a Python package like astor. Doing the rewriting at the AST level would allow us to rename `yaml` to `.yaml` only within import statements and direct references to the imported module, and not anywhere else in the file.
2. Rename the modules by manipulating `sys.modules`, a dict that maps module names as strings to imported modules. Basically I would need to add lines like `sys.modules[old_name] = __import__(new_name)` to the modules copied over by treeshaker. Existing import statements would then work without issues. There are some details to pay attention to here: the module loaded by `__import__(new_name)` may import other modules in turn, so I would need to make sure that those imported modules have keys set in `sys.modules` before any lines like `import <old_name>`. One solution to this could be to track the dependency tree (treeshaker already constructs this tree using modulegraph as part of its normal operation) and add `sys.modules[old_name] = __import__(new_name)` statements for all immediate children of each node on the dependency tree to the top of the module source file corresponding to that node.
3. Make treeshaker copy modules while retaining the nested folder structure of the package. Currently, treeshaker copies all modules into the destination folder with no nesting or subpackages of any kind. However, if a module like `jsonschema.validators` is in the dependency graph, we can copy it to `build_target/jsonschema/validators.py` and add``build_target/jsonschema/__init__.py` as well. Then, end users can add `build_target/` to their `sys.path` and an import statement like `import jsonschema.validators` will work work without any rewriting.

(2) is probably easiest to implement relative to the logic already in treeshaker. In any case, I don't think there's a quick fix for this.

**Closed as completed** 2021-03-15 11:23 UTC

**Comment by lyuben-todorov** [comment] 2021-03-15 11:26
Thank you and sorry for wasting your time, I've fixed my problem by just shedding some python crates that come with python's default installation. I could open a PR to the README to add some information summarising my mistakes and misconseptions about this package.
